[[redirects]]
  from = "/api/groq/*"
  to = "https://api.groq.com/openai/v1/chat/completions"
  status = 200
  force = true
  headers = {Authorization = "Bearer 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"} 